server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/hariMart_ms_order # Updated port for PostgreSQL
    username: postgres
    password: harianbu@3
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  application:
    name: order-service

  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development only
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # Exposes all endpoints (use caution in production)
  endpoint:
    health:
      show-details: always # Displays detailed health information

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      order-service:
        base-config: default
        sliding-window-size: 20 # Custom window size for order-service
        failure-rate-threshold: 40
        wait-duration-in-open-state: 15s

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.type.mapping: orderConfirmation:com.hariSolution.kafkaProducer.OrderConfirmation

application:
  config:
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payment
    user-url: http://localhost:8222/api/v1/users
